package com.bruce121.autoconfigure;

import org.springframework.boot.context.properties.ConfigurationProperties;

import lombok.Getter;
import lombok.Setter;

/**
 * Author: Bruce121
 * Date: 2018-11-29
 */
@Getter
@Setter
@ConfigurationProperties(prefix = "my-activemq")
public class MyActivemqProperties {

    /**
     * Use for conditional annotation
     */
    private boolean enabled;

    /**
     * URL of the ActiveMQ broker. Auto-generated by default.
     */
    private String brokerUrl = "tcp://localhost:61616";

    /**
     * Login user of the broker.
     */
    private String user = "admin";

    /**
     * Login password of the broker.
     */
    private String password = "admin";

}
